---
- name: Download and unpack miniconda.
  get_url:
    url: https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
    dest: "{{ tmp_dir }}/miniconda-installer.sh"
    mode: 0500
  register: miniconda

- name: Install miniconda.
  # The -b flag is for batch mode (i.e. non-interactive).
  shell: "{{ tmp_dir }}/miniconda-installer.sh -b -u -p {{ install_dir }}/miniconda3"
  async: "{{ miniconda_async_timeout }}"
  poll: "{{ async_poll_value_move_on }}"
  register: async_miniconda
